# Generated by Django 4.1.1 on 2022-10-03 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('desc', models.TextField(blank=True)),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='MetricPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('desc', models.TextField(blank=True)),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('value', models.IntegerField()),
                ('start_day', models.DateTimeField(verbose_name='startday')),
                ('end_day', models.DateTimeField(verbose_name='EndDay')),
            ],
        ),
        migrations.CreateModel(
            name='QualityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('desc', models.TextField(blank=True)),
                ('metricplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.metricplan')),
            ],
        ),
        migrations.CreateModel(
            name='GrowPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('desc', models.TextField(blank=True)),
                ('date', models.DateTimeField(verbose_name='Day')),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.crops')),
                ('qualityplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.qualityplan')),
            ],
        ),
    ]
