# Generated by Django 4.1.1 on 2022-10-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_crops_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='metricplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.metricplan'),
        ),
    ]
