# Generated by Django 4.1.1 on 2022-10-06 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crops_metricplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='metricplan',
        ),
    ]
