# Generated by Django 4.1.1 on 2022-10-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_crops_metricplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='user',
            field=models.IntegerField(default=1, verbose_name='Venue Owner'),
        ),
    ]
